// ResetRelease.v

// Generated using ACDS version 25.3.1 100

`timescale 1 ps / 1 ps
module ResetRelease (
		output wire  ninit_done  // ninit_done.ninit_done
	);

	intel_user_rst_clkgate intel_user_rst_clkgate_0 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.ninit_done
	);

endmodule
