// int_line.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module int_line (
		input  wire [9:0]  data,      //      data.datain,    Data input of the memory.The data port is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		output wire [9:0]  q,         //         q.dataout,   Data output from the memory
		input  wire [11:0] wraddress, // wraddress.wraddress, Write address input to the memory.
		input  wire [11:0] rdaddress, // rdaddress.rdaddress, Read address input to the memory.
		input  wire        wren,      //      wren.wren,      Write enable input for address port.The wren signal is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	int_line_ram_2port_2060_r46qrgq ram_2port_0 (
		.data      (data),      //   input,  width = 10,      data.datain
		.q         (q),         //  output,  width = 10,         q.dataout
		.wraddress (wraddress), //   input,  width = 12, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 12, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
